### ISSUE TITLE
[Compat] Chipped compat - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [meeetj/Fabric-Better-Ladders#1]
all chipped ladders have the same texture ( your 3d textures )

maybe for now remove that texture and let the normal chipped texture take in place

or make 3D textures for Chipped

either way would be fine

**Comment by meeetj** [comment]
I uploaded a version without the 3D texture change.

3D textures for Chipped should probably be their own standalone resource pack (my texture as well i guess, but i like having it bundled up in one :D).
I'm not playing with Chipped though, so i probably won't make a pack for it

**Comment by SpigotDE** [comment]
So, technically i (or someone else) could do some 3D textures and they would be used on the chipped ladders (your 3d textures gets overwritten)

**Comment by meeetj** [comment]
For now you can use the version without my 3d texture



As far as i can see with Chipped the vanilla ladder still exists, so that one would in theory keep my 3d model texture
(but better to include that 3d model in the chipped resourcepack you create as well, so you can also just play chipped with that resource pack, without my better ladder mod)

My 3D model is just [this file](https://github.com/meeetj/Fabric-Better-Ladders/blob/master/src/main/resources/assets/minecraft/models/block/ladder.json)

Chipped has its block models under .../assets/chipped/models/block/
-> create a crooked_ladder.json, mossy_ladder,json etc. there with a 3d model like mine



I attached a "texturepack template" that you can just put in your resourcepack folder to work off of:
[your-resourcepack.zip](https://github.com/meeetj/Fabric-Better-Ladders/files/11301305/your-resourcepack.zip)

in there you'll find my ladder.json and a mossy_ladder.json, both just having my 3d model. But then you have the folder structure you can work off of, and how to link it to the right textures inside the .json

**Comment by xR4YM0ND** [comment]
thx , forgot to close.
I managed to make a resourcepack that works.

Thank you so much for your guidance
